development: &default
  adapter: postgresql
  database: scribe_development
  encoding: utf8
  min_messages: warning
  pool: 5
  reaping_frequency: 10
  timeout: 5000


test:
  <<: *default
  database: scribe_test

production: &deploy
  <<: *default
  adapter: postgresql
  database: scribe_production

staging: *deploy
